CREATE USER app_user IDENTIFIED BY "appuser123";

GRANT CREATE SESSION TO app_user;
GRANT CREATE TABLE TO app_user;
GRANT CREATE VIEW TO app_user;
GRANT CREATE PROCEDURE TO app_user;
GRANT CREATE SEQUENCE TO app_user;
GRANT UNLIMITED TABLESPACE TO app_user;

SELECT * FROM USER_TABLES;
SELECT * FROM DBA_USERS;

alter table student_details add CONSTRAINT uq_student UNIQUE (student_id,student_name)
